name: EAS Deploy

on:
  push:
    branches:
      - main # ou outra branch de sua preferência

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies and EAS CLI
        run: |
          npm install
          npm install -g eas-cli

      - name: Authenticate with EAS
        run: echo -e "${{ secrets.EAS_USERNAME }}\n${{ secrets.EAS_PASSWORD }}" | eas login

      - name: Deploy to EAS
        run: eas update --branch preview --message "Deploy"
